apiVersion: v1
kind: Service
metadata:
    name: "personiclecluster-8d69"
    labels:
        app: "personiclecluster-8d69"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "personiclecluster-8d69"